-- Task 95: Internal service request notes and timeline foundation.
--
-- DEV/STAGING APPLY-READY.
-- Purpose:
--   Add lightweight internal technician/dispatcher notes for service_requests
--   and record status changes as chronological timeline entries.
--
-- Security model:
--   - Anonymous users cannot read or write notes.
--   - Authenticated dashboard users can read notes only when they can already
--     read the parent service request through public.can_view_service_request.
--   - Note creation happens through a narrow RPC that validates parent request
--     access and writes only note_type/body/actor metadata.
--   - Status changes continue through update_service_request_status_rpc, which
--     is replaced here to also insert a status_change note.

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.service_request_notes (
  id uuid primary key default gen_random_uuid(),
  service_request_id uuid not null
    references public.service_requests(id)
    on delete cascade,
  created_by_profile_id uuid
    references public.profiles(id)
    on delete set null,
  note_type text not null
    check (note_type in (
      'internal_note',
      'diagnostic',
      'dispatcher_note',
      'parts_note',
      'status_change'
    )),
  body text not null,
  created_at timestamptz not null default now(),

  constraint service_request_notes_body_not_blank_check
    check (length(btrim(body)) > 0),
  constraint service_request_notes_body_length_check
    check (char_length(body) <= 2000)
);

comment on table public.service_request_notes is
  'Task 95 internal service request notes/timeline entries. Dashboard-only; never expose publicly.';
comment on column public.service_request_notes.created_by_profile_id is
  'Authenticated profile that created the note when available. Do not expose publicly.';
comment on column public.service_request_notes.note_type is
  'Lightweight operational note type. status_change entries are generated by status RPC updates.';

create index if not exists service_request_notes_request_created_at_idx
  on public.service_request_notes (service_request_id, created_at desc);
create index if not exists service_request_notes_type_created_at_idx
  on public.service_request_notes (note_type, created_at desc);
create index if not exists service_request_notes_created_by_idx
  on public.service_request_notes (created_by_profile_id)
  where created_by_profile_id is not null;

alter table public.service_request_notes enable row level security;

revoke all on public.service_request_notes from public;
grant select on public.service_request_notes to authenticated;

drop policy if exists "service_request_notes_dashboard_select" on public.service_request_notes;
create policy "service_request_notes_dashboard_select"
on public.service_request_notes
for select
to authenticated
using (public.can_view_service_request(service_request_id));

create or replace function public.add_service_request_note_rpc(
  p_request_id uuid,
  p_note_type text,
  p_body text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted_note public.service_request_notes;
  cleaned_body text;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required.'
      using errcode = '28000';
  end if;

  if p_note_type not in (
    'internal_note',
    'diagnostic',
    'dispatcher_note',
    'parts_note'
  ) then
    raise exception 'Invalid service request note type.'
      using errcode = '22023';
  end if;

  if not public.can_view_service_request(p_request_id) then
    raise exception 'Service request is not accessible for this account.'
      using errcode = '42501';
  end if;

  cleaned_body := left(btrim(coalesce(p_body, '')), 2000);

  if length(cleaned_body) = 0 then
    raise exception 'Service request note body is required.'
      using errcode = '22023';
  end if;

  insert into public.service_request_notes (
    service_request_id,
    created_by_profile_id,
    note_type,
    body
  )
  values (
    p_request_id,
    auth.uid(),
    p_note_type,
    cleaned_body
  )
  returning * into inserted_note;

  return jsonb_build_object(
    'id', inserted_note.id,
    'service_request_id', inserted_note.service_request_id,
    'created_by_profile_id', inserted_note.created_by_profile_id,
    'note_type', inserted_note.note_type,
    'body', inserted_note.body,
    'created_at', inserted_note.created_at
  );
end;
$$;

comment on function public.add_service_request_note_rpc(uuid, text, text) is
  'Task 95 RPC. Adds a dashboard-only internal note to an accessible service request.';

revoke all on function public.add_service_request_note_rpc(uuid, text, text) from public;
grant execute on function public.add_service_request_note_rpc(uuid, text, text) to authenticated;

create or replace function public.update_service_request_status_rpc(
  p_request_id uuid,
  p_next_status text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  previous_status text;
  updated_request public.service_requests;
begin
  if auth.uid() is null then
    raise exception 'Authentication is required.'
      using errcode = '28000';
  end if;

  if p_next_status not in ('new', 'contacted', 'scheduled', 'completed', 'canceled') then
    raise exception 'Invalid service request status.'
      using errcode = '22023';
  end if;

  if not public.can_view_service_request(p_request_id) then
    raise exception 'Service request is not accessible for this account.'
      using errcode = '42501';
  end if;

  select status
  into previous_status
  from public.service_requests
  where id = p_request_id;

  if not found then
    raise exception 'Service request was not found.'
      using errcode = 'P0002';
  end if;

  update public.service_requests
  set
    status = p_next_status,
    updated_at = now()
  where id = p_request_id
  returning * into updated_request;

  if previous_status is distinct from p_next_status then
    insert into public.service_request_notes (
      service_request_id,
      created_by_profile_id,
      note_type,
      body
    )
    values (
      p_request_id,
      auth.uid(),
      'status_change',
      'Status changed from '
        || initcap(replace(previous_status, '_', ' '))
        || ' to '
        || initcap(replace(p_next_status, '_', ' '))
        || '.'
    );
  end if;

  return jsonb_build_object(
    'id', updated_request.id,
    'status', updated_request.status,
    'updated_at', updated_request.updated_at
  );
end;
$$;

comment on function public.update_service_request_status_rpc(uuid, text) is
  'Task 95 update. Updates service request status and writes a status_change timeline note when status changes.';

revoke all on function public.update_service_request_status_rpc(uuid, text) from public;
grant execute on function public.update_service_request_status_rpc(uuid, text) to authenticated;

-- No INSERT/UPDATE/DELETE grants are added for service_request_notes. Browser
-- writes should go through the narrow RPCs above.
